apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: zk-hs
    labels:
      app: zk
  spec:
    ports:
    - port: 2888
      name: server
    - port: 3888
      name: leader-election
    clusterIP: None
    selector:
      app: zk

- apiVersion: v1
  kind: Service
  metadata:
    name: zk-cs
    labels:
      app: zk
  spec:
    ports:
    - port: 2181
      name: client
    selector:
      app: zk

- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    annotations:
    name: zk
    namespace: anair-zk
  spec:
    podManagementPolicy: Parallel
    replicas: 3
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: zk
    serviceName: zk-hs
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: zk
      spec:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - zk
                topologyKey: kubernetes.io/hostname
        containers:
          - command:
              - sh
              - '-c'
              - >-
                start-zookeeper --servers=3 --data_dir=/var/lib/zookeeper/data
                --data_log_dir=/var/lib/zookeeper/data/log
                --conf_dir=/opt/zookeeper/conf --client_port=2181
                --election_port=3888 --server_port=2888 --tick_time=2000
                --init_limit=10 --sync_limit=5 --heap=512M --max_client_cnxns=60
                --snap_retain_count=3 --purge_interval=12
                --max_session_timeout=40000 --min_session_timeout=4000
                --log_level=WARN
            image: 'docker-registry.default.svc:5000/anair-zk/zookeeper:3.4.10-1'
            imagePullPolicy: Always
            livenessProbe:
              exec:
                command:
                  - sh
                  - '-c'
                  - zookeeper-ready 2181
              failureThreshold: 3
              initialDelaySeconds: 10
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 5
            name: kubernetes-zookeeper
            ports:
              - containerPort: 2181
                name: client
                protocol: TCP
              - containerPort: 2888
                name: server
                protocol: TCP
              - containerPort: 3888
                name: leader-election
                protocol: TCP
            readinessProbe:
              exec:
                command:
                  - sh
                  - '-c'
                  - zookeeper-ready 2181
              failureThreshold: 3
              initialDelaySeconds: 10
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 5
            resources:
              requests:
                cpu: 500m
                memory: 1Gi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
              - mountPath: /var/lib/zookeeper
                name: datadir
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          fsGroup: 1000
          runAsUser: 1000
        terminationGracePeriodSeconds: 30
    updateStrategy:
      type: RollingUpdate
    volumeClaimTemplates:
      - metadata:
          creationTimestamp: null
          name: datadir
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: glusterfs-storage
      