apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    prometheus.io/port: '24231'
    prometheus.io/scheme: http
    prometheus.io/scrape: 'true'
  labels:
    component: fluentd
    logging-infra: fluentd
    provider: openshift
  name: logging-fluentd
  namespace: logging
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: fluentd
      provider: openshift
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
      creationTimestamp: null
      labels:
        component: fluentd
        logging-infra: fluentd
        provider: openshift
      name: fluentd-elasticsearch
    spec:
      containers:
        - env:
            - name: K8S_HOST_URL
              value: 'https://kubernetes.default.svc.cluster.local'
            - name: ES_HOSTS
              value: >-
                https://{{ES_HOSTNAME_1}}:9200,https://{{ES_HOSTNAME_2}}:9200
            - name: ES_HOST
              value: {{ES_HOSTNAME_1}}
            - name: ES_PORT
              value: '9200'
            - name: ES_SSL_VERSION
              value: TLSv1_2
            - name: OPS_HOST
              value: {{ES_HOSTNAME_1}}
            - name: OPS_PORT
              value: '9200'
            - name: ES_SCHEME
              value: https
            - name: ES_CA
              value: /etc/fluent/keys/root-ca.pem
            - name: ES_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: opendistro-es-cred
            - name: ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: opendistro-es-cred
            - name: JOURNAL_SOURCE
            - name: JOURNAL_READ_FROM_HEAD
            - name: BUFFER_QUEUE_LIMIT
              value: '64'
            - name: BUFFER_SIZE_LIMIT
              value: 16m
            - name: FLUENTD_CPU_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: fluentd-elasticsearch
                  divisor: '0'
                  resource: limits.cpu
            - name: FLUENTD_MEMORY_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: fluentd-elasticsearch
                  divisor: '0'
                  resource: limits.memory
            - name: FILE_BUFFER_LIMIT
              value: 1Gi
          image: 'registry.access.redhat.com/openshift3/logging-fluentd:v3.10.14'
          imagePullPolicy: IfNotPresent
          name: fluentd-elasticsearch
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 1Gi
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /run/log/journal
              name: runlogjournal
            - mountPath: /var/log
              name: varlog
            - mountPath: /var/lib/docker
              name: varlibdockercontainers
              readOnly: true
            - mountPath: /etc/fluent/configs.d/user
              name: config
              readOnly: true
            - mountPath: /etc/fluent/keys
              name: certs
              readOnly: true
            - mountPath: /etc/docker-hostname
              name: dockerhostname
              readOnly: true
            - mountPath: /etc/localtime
              name: localtime
              readOnly: true
            - mountPath: /etc/sysconfig/docker
              name: dockercfg
              readOnly: true
            - mountPath: /etc/docker
              name: dockerdaemoncfg
              readOnly: true
            - mountPath: /etc/origin/node
              name: originnodecfg
              readOnly: true
            - mountPath: /var/lib/fluentd
              name: filebufferstorage
      dnsPolicy: ClusterFirst
      nodeSelector:
        logging-infra-fluentd: 'true'
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: aggregated-logging-fluentd
      serviceAccountName: aggregated-logging-fluentd
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /run/log/journal
            type: ''
          name: runlogjournal
        - hostPath:
            path: /var/log
            type: ''
          name: varlog
        - hostPath:
            path: /var/lib/docker
            type: ''
          name: varlibdockercontainers
        - configMap:
            defaultMode: 420
            name: logging-fluentd
          name: config
        - name: certs
          secret:
            defaultMode: 420
            secretName: opendistro-es-cert
        - hostPath:
            path: /etc/hostname
            type: ''
          name: dockerhostname
        - hostPath:
            path: /etc/localtime
            type: ''
          name: localtime
        - hostPath:
            path: /etc/sysconfig/docker
            type: ''
          name: dockercfg
        - hostPath:
            path: /etc/origin/node
            type: ''
          name: originnodecfg
        - hostPath:
            path: /etc/docker
            type: ''
          name: dockerdaemoncfg
        - hostPath:
            path: /var/lib/fluentd
            type: ''
          name: filebufferstorage
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate

